config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :records
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :text, presence: true
  validates :image, presence: true

  def self.search(search)
    if search != ''
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :search]
  before_action :set_tweet, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, only: [:edit]

  def index
    @tweets = Tweet.includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path(@tweet)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private

  def tweet_params
    params.require(:tweet).permit(:image, :title, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
    redirect_to(root_path) unless @user == current_user
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_area :title, class: :form__text, id:"tweet_title" %>
  </div>

  <div class="field">
    <%= f.label :text, "テキスト" %><br />
    <%= f.text_area :text, class: :form__text, id:"tweet_text" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"tweet_image" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= button_to 'トップページ', root_path, method: :get %>
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ツイート編集</h2>
      <%# 部分テンプレートでツイートフォームを表示する %>
      <%= render partial: "form", locals: { tweet: @tweet } %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<link href="https://fonts.googleapis.com/css?family=DM+Sans:400,500,700&display=swap" rel="stylesheet">
<div class="app-wrapper">
  <div class="left-area hide-on-mobile">
    <div class="app-header">Aller<br>
      <span class="inner-text">〜食物アレルギーの助けに〜</span>
      <button class="close-menu">
        <svg width="24" height="24" fill="none" stroke="#51a380" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="feather feather-x">
          <defs />
          <path d="M18 6L6 18M6 6l12 12" />
        </svg>
      </button>
    </div>
    <div class="left-area-content">
      <% if user_signed_in? %>
      <div class="profile">
      <%= image_tag '/assets/sample.jpeg' %>
        <div class="profile-info">
          <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: "profile-name"%>
        </div>
      </div>
      <% end %>
      <div class="page-link-list">
        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id), class:"item-link" do %>
            <svg class="link-icon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="feather feather-home" viewBox="0 0 24 24">
              <defs />
              <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
              <path d="M9 22V12h6v10" /></svg>
          マイページ
          <% end %>
          <%= link_to records_path(current_user.id), class:"item-link" do %>
            <svg class="link-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart">
            <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z" /></svg>
          記録
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class:"item-link" do %>
            <svg class="link-icon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="feather feather-home" viewBox="0 0 24 24">
              <defs />
              <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
              <path d="M9 22V12h6v10" /></svg>
          マイページ
          <% end %>
          <%= link_to new_user_session_path, class:"item-link" do %>
            <svg class="link-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart">
            <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z" /></svg>
          記録
          <% end %>
        <% end %>

        <a href="#" class="item-link" id="pageLink">
          <svg class="link-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-play">
            <path d="M5 3l14 9-14 9V3z" />
          </svg>
          おすすめメニュー</a>
        <a href="#" class="item-link" id="pageLink">
          <svg class="link-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list">
            <path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01" />
          </svg>
          寄付</a>
      </div>


    </div>
    <% if user_signed_in? %>
      <%= link_to new_record_path do %>
      <button class="btn-invite">記録する</button>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path do %>
      <button class="btn-invite">記録する</button>
      <% end %>
    <% end %>
  </div>
  <div class="right-area">
    <div class="right-area-upper">
    <%# ツイート検索部分 %>
      <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
      <% end %>

    <%# 新規登録やログインログアウト部分 %>
      <div class="action-buttons-wrapper">
        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id), class: "user-nickname" do%>
            <button class="action-buttons btn-record"><%= current_user.nickname%></button>
          <% end %>
          <%= link_to destroy_user_session_path , method: :delete, class: "logout" do%>
            <button class="action-buttons btn-upload">ログアウト</button>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "login" do%>
            <button class="action-buttons btn-record">ログイン</button>
          <% end %>
          <%= link_to new_user_registration_path, class: "sign-up" do%>
            <button class="action-buttons btn-upload">新規登録</button>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="page-right-content">
      <div class="content-line content-line-hero">
        <div class="slider-wrapper owl-carousel owl-theme" id="owl-slider-1">
          <div class="item hero-img-wrapper img-1">
            <div class="upload-text-wrapper">
              <p class="upload-text-info">Let's share it with everyone
              <% if user_signed_in? %>
              <%= link_to new_tweet_path do%>
                <button class="btn-new-1">つぶやき</button>
              <% end %>
                <button class="btn-new-2">寄付募集</button>
              <% end %>
              </p>
            </div>
            <%= image_tag '/assets/food',:size => '500x300'%>
          </div>
        </div>
      </div>

    <%# ツイート表示部分 %>
      <div class="content-line content-line-list">
        <div class="line-header">
          <span class="header-text">つぶやき</span>
        </div>
        <div id="owl-slider-2" class="slider-wrapper owl-carousel" style="overflow-x: scroll;">
          <% @tweets.each do |tweet| %>
          <div class="item video-box-wrapper">
            <div class="img-preview">
            <%= link_to image_tag(tweet.image), tweet_path(tweet.id) %>
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header"><%= tweet.title %></p>
              <p class="video-description-subheader"><%= link_to "by #{tweet.user.nickname}", user_path(tweet.user.id) %></p>
              <p class="video-description-info">いいね <span><%= tweet.created_at.strftime('%Y/%m/%d %H:%M:%S') %></span></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>

    <%# 寄付募集表示部分 %>
      <div class="content-line content-line-list">
        <div class="line-header">
          <span class="header-text">寄付</span>
        </div>
        <div id="owl-slider-3" class="slider-wrapper owl-carousel">
          <div class="item video-box-wrapper">
            <div class="img-preview">
              <img src="https://images.unsplash.com/photo-1494252713559-f26b4bf0b174?ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80" alt="video">
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header">Minimal Photography</p>
              <p class="video-description-subheader">By July</p>
              <p class="video-description-info">116K views <span>1 hour ago</span></p>
            </div>
          </div>
          <div class="item video-box-wrapper">
            <div class="img-preview">
              <img src="https://images.unsplash.com/photo-1524678714210-9917a6c619c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=2249&q=80" alt="video">
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header">Puppet Theatre</p>
              <p class="video-description-subheader">By July</p>
              <p class="video-description-info">116K views <span>1 hour ago</span></p>
            </div>
          </div>
          <div class="item video-box-wrapper">
            <div class="img-preview">
              <img src="https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-1.2.1&auto=format&fit=crop&w=2168&q=80" alt="video">
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header">Road Trip</p>
              <p class="video-description-subheader">By Wallace</p>
              <p class="video-description-info">116K views <span>1 hour ago</span></p>
            </div>
          </div>
          <div class="item video-box-wrapper">
            <div class="img-preview">
              <img src="https://images.unsplash.com/photo-1502136969935-8d8eef54d77b?ixlib=rb-1.2.1&auto=format&fit=crop&w=2249&q=80" alt="video">
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header">Young Folks</p>
              <p class="video-description-subheader">By Peter</p>
              <p class="video-description-info">116K views <span>1 hour ago</span></p>
            </div>
          </div>
          <div class="item video-box-wrapper">
            <div class="img-preview">
              <img src="https://images.unsplash.com/photo-1490535004195-099bc723fa1f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3280&q=80" alt="video">
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header">Minimal Photography</p>
              <p class="video-description-subheader">By July</p>
              <p class="video-description-info">116K views <span>1 hour ago</span></p>
            </div>
          </div>
          <div class="item video-box-wrapper">
            <div class="img-preview">
              <img src="https://images.unsplash.com/photo-1522410818928-5522dacd5066?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80" alt="video">
            </div>
            <div class="video-description-wrapper">
              <p class="video-description-header">Puppet Theatre</p>
              <p class="video-description-subheader">By July</p>
              <p class="video-description-info">116K views <span>1 hour ago</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<%= button_to 'トップページ', root_path, method: :get %>
<div class="form__wrapper">
  <h2 class="page-heading">新規ツイート投稿</h2>
    <%= render partial: 'form', locals: { tweet: @tweet } %>
</div>

app/views/tweets/search.html.erb
<%= button_to 'トップページ', root_path, method: :get %>

<div id="owl-slider-2" class="slider-wrapper owl-carousel" style="overflow-x: scroll;">
  <% @tweets.each do |tweet| %>
    <div class="item video-box-wrapper">
      <div class="img-preview">
      <%= link_to image_tag(tweet.image), tweet_path(tweet.id) %>
      </div>
      <div class="video-description-wrapper">
        <p class="video-description-header"><%= tweet.title %></p>
        <p class="video-description-subheader"><%= link_to "by #{tweet.user.nickname}", user_path(tweet.user.id) %></p>
        <p class="video-description-info">いいね <span><%= tweet.created_at.strftime('%Y/%m/%d %H:%M:%S') %></span></p>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="prototype__wrapper">
<%= button_to 'トップページ', root_path, method: :get %>
  <p class="prototype__hedding">
    <%= @tweet.title%>
  </p>
  <%= link_to "by#{@tweet.user.nickname}", user_path(@tweet.user.id), class: :prototype__user %>
  <%# 投稿者とログインしているユーザーが同じであれば以下を表示する %>
    <div class="prototype__manage">
      <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <%= link_to "編集する", edit_tweet_path(@tweet.id), class: :prototype__btn %>
        <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, class: :prototype__btn %>
      <% end %>
    </div>
  <%# // 投稿者とログインしているユーザーが同じであれば上記を表示する %>
  <div class="prototype__image">
    <%= image_tag @tweet.image %>
  </div>
  <div class="prototype__body">
    <div class="prototype__detail">
      <p class="detail__title">テキスト</p>
      <p class="detail__message">
        <%= @tweet.text %>
      </p>
    </div>
  </div>
  <div class="prototype__comments">
    <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
    <% if user_signed_in? %>
      <%= form_with model: [@tweet,@comment], local: true do |f|%>
        <div class="field">
          <%= f.label :text, "コメント" %><br />
          <%= f.text_field :text, id:"comment_text" %>
        </div>
        <div class="actions">
          <%= f.submit "送信する", class: :form__btn  %>
        </div>
      <% end %>
    <% end %>
    <%# // ログインしているユーザーには上記を表示する %>
    <ul class="comments_lists">
      <%# 投稿に紐づくコメントを一覧する処理を記述する %>
      <% @comments.each do |comment| %>
        <li class="comments_list">
            <%= comment.text %>
            <%= link_to comment.user.nickname, user_path(@tweet.user.id), class: :comment_user %>
        </li>
      <%end%>
      <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
    </ul>
  </div>
</div>