config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :records
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :age
  belongs_to :unit
  belongs_to :state

  validates :datetime, presence: true
  validates :food, presence: true

  # ジャンルの選択が「--」の時は保存できないようにする
  validates :age_id, numericality: { other_than: 1, message: '年齢を選択してください' }
  validates :state_id, numericality: { other_than: 1, message: '食物アレルギーの有無を選択してください' }
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, only: [:edit]

  def index
    @records = Record.order('created_at DESC')
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to root_path(@record)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @record.update(record_params)
      redirect_to record_path
    else
      render :edit
    end
  end

  def destroy
    @record.destroy
    redirect_to root_path
  end

  private

  def record_params
    params.require(:record).permit(:datetime, :age_id, :food, :quantity, :unit_id, :state_id,
                                   :note).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find(params[:id])
  end

  def move_to_index
    @record = Record.find(params[:id])
    @user = @record.user
    redirect_to(root_path) unless @user == current_user
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_with model: @record, local: true do |f| %>
  <div class="record-box">
    <h1 class="page-heading">食事を記録する</h1>
      <div class="field">
        <%= f.label :datetime, '日時  (必須)', class: 'control-label' %><br>
        <%= f.datetime_field :datetime, class: 'form-control' %>
      </div>

      <div class="field">
         <%= f.label :age_id, '年齢  (必須)', class: 'control-label' %>
         <%= f.collection_select(:age_id, Age.all, :id, :name, {}, {class:"select-box"}) %>
      </div>

      <div class="field">
        <%= f.label :food, '食べたもの  (必須)', class: 'control-label' %><br>
        <%= f.text_area :food, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :quantity, 'どのくらい、量  (任意)', class: 'control-label' %><br>
        <%= f.text_area :quantity, class: 'form-control' %>
      </div>

      <div class="field">
         <%= f.label :unit_id, '単位  (任意)', class: 'control-label' %>
         <%= f.collection_select(:unit_id, Unit.all, :id, :name, {}, {class:"select-box"}) %>
      </div>

      <div class="field">
         <%= f.label :state_id, '食べたときの様子  (必須)', class: 'control-label' %>
         <%= f.collection_select(:state_id, State.all, :id, :name, {}, {class:"select-box"}) %>
      </div>

      <div class="field">
        <%= f.label :note, '備考  (任意)', class: 'control-label' %><br>
        <%= f.text_area :note, class: 'form-control' %>
      </div>

        <%= f.submit "記録する" ,class:"btn" %>
  </div>
<% end %>

app/views/records/edit.html.erb
<div class="record__button">
  <%= button_to 'トップページ', root_path, method: :get %>
  <%= button_to '記録一覧ページ', records_path, method: :get %>
</div>
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">記録編集</h2>
      <%# 部分テンプレートで記録フォームを表示する %>
      <%= render partial: "form", locals: { record: @record } %>
    </div>
  </div>
</div>

app/views/records/index.html.erb
<div class="record__button">
  <%= button_to 'トップページ', root_path, method: :get %>
  <%= button_to '新しく記録する', new_record_path, method: :get %>
</div>

<ul class='record-lists'>
<%# if current_user.id == @record.user_id %>
  <% @records.each do |record| %>
    <% if current_user.id == record.user_id %>
      <li class='list'>
        <%= link_to record_path(record.id) do %>
          <div class='record-info'>
            <p class='datetime'>
              <%= record.datetime %>
            </p>
            <h3 class='record-content'>
              <%= record.food %>
              <%= record.quantity %>
              <%= record.unit[:name] %>
              <%= record.state[:name] %>
            </h3>
          </div>
        <% end %>
      </li>
    <% else %>
      <h1>記録をしよう!!</h1>
    <% end %>
  <%end%>
</ul>

app/views/records/new.html.erb
<%= button_to 'トップページ', root_path, method: :get %>
<%= render partial: 'form', locals: { record: @record } %>

app/views/records/show.html.erb
<div class="record__wrapper">
  <div class="record__button">
    <%= button_to 'トップページ', root_path, method: :get %>
    <%= button_to '記録一覧ページ', records_path, method: :get %>
  </div>
  <p class="prototype__hedding">
    <%= @record.datetime %><br>
    <%= @record.age[:name] %>
    <%= @record.food %>
    <%= @record.quantity %>
    <%= @record.unit[:name] %>
    <%= @record.state[:name] %>
    <%= @record.note %>
  </p>
  <%# 記録者とログインしているユーザーが同じであれば以下を表示する %>
    <div class="prototype__manage">
      <% if user_signed_in? && current_user.id == @record.user_id %>
        <%= link_to "編集する", edit_record_path(@record.id), class: :prototype__btn %>
        <%= link_to "削除する", record_path(@record.id), method: :delete, class: :prototype__btn %>
      <% end %>
    </div>
  <%# // 記録者とログインしているユーザーが同じであれば上記を表示する %>
</div>